### PR TITLE
Add some niceties to help new people quickly run code

### PR DESCRIPTION
**Pull request by rpc333**
1.  Add a stub README file to help people run code
2. New module, `check_environ` for loading env variables cleanly/immediately find out what you don't have set
3. Check in template `.env` file that new people can fill in to set env variables that way
4. Add `requirements.txt` file to help people install various Python dependencies
5. Add `venv` to `.gitignore` so people following instructions won't have their virtual environment dragged in to git

**NOTE**
I generated the `requirements.txt` file using `pipreqs` and I'm not sure everything is totally needed there. Sanity check before we merge this would be a good idea

### CODE REVIEW

**Comment by rpc333** [comment]
@Jemoka tell me if this looks good, especially the `requirements.txt` file which I autogen'd/have limited context on

**Comment by Jemoka** [comment]
Looks awesome. I will test the `requirements.txt` and merge after that.

**Comment by Jemoka** [comment]
Actually, still missing is a note about provisioning Elastic. I will get that set up shortly.

**Comment by rpc333** [comment]
> Looks awesome. I will test the `requirements.txt` and merge after that.

Yeah I've done some local testing and had to add in `openai` and `tiktoken` manually but it seems ok now.

> Actually, still missing is a note about provisioning Elastic. I will get that set up shortly.

I've been testing with the Elastic Cloud Trial and so far only "gotcha" was being pushed into using `cloud_id` instead of the URL form. Might tweak `check_environ` to gracefully handle either a URL or CLOUD_ID later, but don't want to clutter this PR.

ES docs I've been going off of:
 https://www.elastic.co/guide/en/welcome-to-elastic/current/getting-started-general-purpose.html#gp-gs-add-data
https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/connecting.html

**Comment by Jemoka** [comment]
Yes, but search will break silent if you don't seed the index: elastic will index your embeddings as a numerical array and not a dense vector, which means KNNs will return nothing.

**Comment by rpc333** [comment]
> Yes, but search will break silent if you don't seed the index: elastic will index your embeddings as a numerical array and not a dense vector, which means KNNs will return nothing.

Yeah I also had to manually do the `_seed_schema` thing, was thinking might pull some of that into a little helper script or something so it's not buried in `playground.py`

(Again, can just tack that on later, just conscious that Jacob wants to test this out himself too and he's less familiar with Python vagueries)

**Comment by Jemoka** [comment]
Ah ok. Wonderful. I will add a note about `_seed_schema(es)`, but yes eventually a setup script is nice.
I usually orchestrate this using something like make, so users can just call make init and have everything happen. I'd love to know what the standard tooling looks like.

**Comment by rpc333** [comment]
If you have a makefile already written, might make sense to just check it in?

For other projects in the past I've written little bash scripts to help people install a virtualenv + dependencies all in one go, but that was just me trying to make it easy for teammates who were less comfortable with command line. Whatever works, works 🤷

**Comment by Jemoka** [comment]
Don't have a makefile yet, and definitely bash scripts makes sense. I will work on improving the main `__call__()` output first to be more useful, and then can work on this.

**Comment by rpc333** [comment]
Let's not worry about adding too much more right now, I think this should be a decent enough boost to newbies for now. If other people stumble they can add the things they had trouble with. Human-driven discovery!

**Comment by rpc333** [comment]
(Leaving this for you to merge if you're happy with it; can always add more in follow-ups)

**Comment by Jemoka** [comment]
One more thing: I don't really like how an example `.env` is committed here. Perhaps we can make an `.env.example`?

**Comment by Jemoka** [comment]
gotta run, but will work more on this later. good first draft for now.

**Pull request merged**
